# Project Configuration
project:
  name: "Macro Announcement Effects on Crypto vs Stock Markets"
  version: "1.0.0"
  description: "Research project analyzing the effect of macroeconomic announcements on cryptocurrency vs U.S. stock market returns, volatility, and trading volume"

# Data Collection Configuration
data_collection:
  # Adjusted start date to avoid structural missing data for newer cryptocurrencies
  # Start date: 2020-09-01 (when all major cryptocurrencies are available)
  # This provides 5 years of complete data with minimal structural missingness
  start_date: "2020-09-01"
  # End date: defaults to current date if not specified
  end_date: null

# Data Sources Configuration
data_sources:
  # Free FRED data (optional API key for higher limits)
  fred:
    api_key: null  # Optional: Set in environment variables for higher rate limits
    base_url: "https://fred.stlouisfed.org/graph/fredgraph.csv"
    
  # Free Yahoo Finance data
  yahoo_finance:
    base_url: "https://finance.yahoo.com"
    
  # Free CoinGecko API (rate limited without key)
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    api_key: null  # Optional: for higher rate limits
    
  # Free economic calendar sources
  economic_calendar:
    sources:
      - "https://www.federalreserve.gov/newsevents/calendar.htm"
      - "https://www.bls.gov/schedule/"
      - "https://www.census.gov/economic-indicators/"
      
  # Cryptocurrency exchanges (free public APIs)
  crypto:
    exchanges:
      - binance  # Free public API
      - coinbase  # Free public API
    symbols:
      - BTC-USD   # Bitcoin
      - ETH-USD   # Ethereum
      - BNB-USD   # Binance Coin
      - XRP-USD   # Ripple
      - ADA-USD   # Cardano
      - SOL-USD   # Solana
      - DOGE-USD  # Dogecoin
      - MATIC-USD # Polygon
      - DOT-USD   # Polkadot
      - AVAX-USD  # Avalanche
      
  # Stock market data (free via Yahoo Finance)
  stocks:
    symbols:
      # Major US Indices
      - "^GSPC"   # S&P 500
      - "^DJI"    # Dow Jones Industrial Average
      - "^IXIC"   # NASDAQ Composite
      - "^RUT"    # Russell 2000
      # Fixed Income
      - "^TNX"    # 10-Year Treasury Yield
      - "^FVX"    # 5-Year Treasury Yield
      - "^TYX"    # 30-Year Treasury Yield
      # Currency
      - "DX-Y.NYB"    # USD Index
      - "EURUSD=X"    # EUR/USD
      - "JPY=X"       # USD/JPY
      - "GBP=X"       # GBP/USD
      # Commodities
      - "GC=F"    # Gold Futures
      - "SI=F"    # Silver Futures
      - "CL=F"    # Crude Oil Futures
      # Sector ETFs
      - "XLF"     # Financial Select Sector SPDR
      - "XLK"     # Technology Select Sector SPDR
      - "XLE"     # Energy Select Sector SPDR
      - "XLV"     # Health Care Select Sector SPDR
      - "XLI"     # Industrial Select Sector SPDR
      # Individual Stocks (Tech & Finance)
      - "AAPL"    # Apple
      - "MSFT"    # Microsoft
      - "GOOGL"   # Alphabet
      - "AMZN"    # Amazon
      - "TSLA"    # Tesla
      - "JPM"     # JPMorgan Chase
      - "BAC"     # Bank of America
      - "GS"      # Goldman Sachs

# Economic Indicators to Track
economic_indicators:
  monetary_policy:
    - FOMC_meetings
    - interest_rate_decisions
    - QE_announcements
    
  employment:
    - UNRATE        # Unemployment Rate
    - PAYEMS        # Nonfarm Payrolls
    - CIVPART       # Labor Force Participation Rate
    
  inflation:
    - CPIAUCSL      # Consumer Price Index
    - CPILFESL      # Core CPI
    - PCEPI         # PCE Price Index
    - PCEPILFE      # Core PCE
    
  gdp:
    - GDP           # Gross Domestic Product
    - GDPC1         # Real GDP
    
  other:
    - DGS10         # 10-Year Treasury Rate
    - DEXUSEU       # USD/EUR Exchange Rate

# Analysis Parameters
analysis:
  # Synthetic data policy (P0 FIX)
  # When true, allows synthetic fallback results when real data is insufficient
  # When false (default), analysis will fail fast with clear error messages
  allow_synthetic: false
  
  # Timezone policy for data alignment (P0 FIX)
  # 'naive' - use timezone-naive timestamps for daily data (recommended for cross-source alignment)
  # 'UTC' - use UTC-aware timestamps (only for intraday or when all sources support it)
  timezone_policy: 'naive'
  
  # Surprise calculation methodology (P1 DOCUMENTATION)
  # When true, marks columns derived from historical means as 'proxy_surprise_'
  # Real forecast-based surprises should be preferred for publication-grade analysis
  mark_proxy_surprises: true
  
  # Event study windows
  event_windows:
    intraday:
      pre_minutes: 60
      post_minutes: 60
    daily:
      pre_days: 1
      post_days: 3
      
  # Return calculation
  returns:
    method: "log"  # log or simple
    frequency: "1min"  # for intraday analysis
    
  # Volatility estimation
  volatility:
    method: "realized"  # realized, garch, etc.
    annualization_factor: 252
    
  # Regression specifications
  regressions:
    controls:
      - lagged_returns
      - lagged_volatility
      - treasury_yield
      - usd_index
    
  # VAR model
  var:
    max_lags: 5
    ic_criterion: "aic"  # aic, bic, hqic
    
# Statistical Tests
statistics:
  significance_level: 0.05
  bootstrap_iterations: 1000
  var_confidence_intervals: [0.05, 0.95]

# Output Configuration
output:
  results_dir: "results"
  figures_dir: "results/figures"
  tables_dir: "results/tables"
  models_dir: "results/models"
  
  figure_format: "png"
  figure_dpi: 300
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/research.log"
  directory: "logs"
  console_output: true
  file_rotation: true
  max_file_size: 10485760  # 10MB
  backup_count: 5